version: '3.8'

services:
  # MongoDB Database
  mongodb:
    image: mongo:6.0
    container_name: mental-health-mongodb
    restart: unless-stopped
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: password
      MONGO_INITDB_DATABASE: mental-health-matcher
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    networks:
      - mental-health-network

  # Backend API
  server:
    build:
      context: ./server
      dockerfile: Dockerfile
    container_name: mental-health-server
    restart: unless-stopped
    environment:
      - NODE_ENV=production
      - PORT=5000
      - MONGODB_URI=mongodb://admin:password@mongodb:27017/mental-health-matcher?authSource=admin
      - JWT_SECRET=your-super-secret-jwt-key-change-this-in-production
      - GEMINI_API_KEY=${GEMINI_API_KEY}
      - CORS_ORIGIN=http://localhost:3000
    ports:
      - "5000:5000"
    depends_on:
      - mongodb
    networks:
      - mental-health-network

  # Frontend Client
  client:
    build:
      context: ./client
      dockerfile: Dockerfile
    container_name: mental-health-client
    restart: unless-stopped
    environment:
      - VITE_API_URL=http://localhost:5000
      - VITE_SOCKET_URL=http://localhost:5000
      - VITE_APP_NAME=Mental Health Support Matcher
      - VITE_APP_VERSION=1.0.0
    ports:
      - "3000:3000"
    depends_on:
      - server
    networks:
      - mental-health-network

volumes:
  mongodb_data:

networks:
  mental-health-network:
    driver: bridge
